### ISSUE TITLE
Does not start, writes an error

### ISSUE THREAD

**Issue by EpicNet** [snoonetIRC/bnc-bot#3]
> Ubuntu Server 18.04 - Python version 2.7 + 3.8 installed

$ sudo apt-get install python-pip
$ pip install -Ur requirements.txt
$ python -m bncbot

Error:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/bot/bnc-bot/bncbot/__main__.py", line 2, in <module>
>     import asyncio
> ImportError: No module named asyncio

What needs to be done to start the bot?

**Comment by examknow** [comment]
You're running the bot with python 2.7 when the bot requires at least python 3.6 in order to run. Try running with a recent version of python.
